### ISSUE TITLE
Remove functionality that should be delegated to the OpenTelemetry SDK / Exporters

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-auto-instr-java#16]
Remove functionality that should be delegated to the OpenTelemetry SDK / Exporters:

- [x] [Sampling](https://github.com/open-telemetry/opentelemetry-auto-instr-java/tree/b93e14291db75b2cfac2ad4a1e434285a5bd6d09/dd-trace-ot/src/main/java/datadog/trace/common/sampling) (#17)
- [x] [Trace context propagation formats](https://github.com/open-telemetry/opentelemetry-auto-instr-java/tree/b93e14291db75b2cfac2ad4a1e434285a5bd6d09/dd-trace-ot/src/main/java/datadog/opentracing/propagation) (#24)
- [x] [Service name split by tags](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/b93e14291db75b2cfac2ad4a1e434285a5bd6d09/dd-trace-api/src/main/java/datadog/trace/api/Config.java#L74) (#20)
- [x] [Service name mappings](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/b93e14291db75b2cfac2ad4a1e434285a5bd6d09/dd-trace-api/src/main/java/datadog/trace/api/Config.java#L56) (#23)
- [x] [Trace interceptors](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/b93e14291db75b2cfac2ad4a1e434285a5bd6d09/dd-trace-api/src/main/java/datadog/trace/api/interceptor/TraceInterceptor.java) (#21)
- [x] [Exporter](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/b93e14291db75b2cfac2ad4a1e434285a5bd6d09/dd-trace-ot/src/main/java/datadog/trace/common/writer) (#25)
- [x] [Report hostname](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/b93e14291db75b2cfac2ad4a1e434285a5bd6d09/dd-trace-api/src/main/java/datadog/trace/api/Config.java#L66) (#31)
- [x] [Globally applied tags](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/b93e14291db75b2cfac2ad4a1e434285a5bd6d09/dd-trace-api/src/main/java/datadog/trace/api/Config.java#L57-L59) (#32, #42)
- [x] [Remove tag decorators](https://github.com/open-telemetry/opentelemetry-auto-instr-java/tree/b93e14291db75b2cfac2ad4a1e434285a5bd6d09/dd-trace-ot/src/main/java/datadog/opentracing/decorators) (#33, #34, #36, #37, #38, #39)

**Comment by trask** [comment]
For the [Tag decorators](https://github.com/open-telemetry/opentelemetry-auto-instr-java/tree/b93e14291db75b2cfac2ad4a1e434285a5bd6d09/dd-trace-ot/src/main/java/datadog/opentracing/decorators), it's not clear to me whether this functionality should eventually be absorbed by the individual instrumentations, or by the SDK / Exporter, or a mix.

So thinking of keeping the tag decorators mostly as is for now.

**Comment by trask** [comment]
I've looked at the decorators in more detail, and ready to go ahead and remove them, absorbing a bit of their functionality into the individual instrumentation where it seems appropriate.

**Comment by trask** [comment]
Closing, I think this issue is completed now! A few more things will fall out as part of #6 (Remove OpenTracing interoperability) and #43 (Change instrumentation to use OpenTelemetry API indirectly).
