### ISSUE TITLE
Things to clean up after updating to opentelemetry-java 0.3.0

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-auto-instr-java#76]
Things to clean up after updating to the next API/SDK release:

- [x] remove all the null conditionals surrounding calls to `setAttribute` (done in #257)
- [x] set attributes directly on the span builder where possible (instead of on the created span) (moved to #303)
- [x] remove try catch blocks around `HttpTraceContext::extract` (probably need to do this and handle the API change at the same time as updating to the next API/SDK release) (done in #257)
- [x] Various compilation errors, e.g. naming changes: Factory --> Provider (done in #257)
- [x] Use the new SpanExporterFactory and Config interfaces (https://github.com/open-telemetry/opentelemetry-java/pull/912) (done in #285)
